github: null
acces-token: ENC[AES256_GCM,data:yuyljbkfofa7b4flzsJKqUSPUoLNWRvw61PORx+z5d7JvXiA9M8bJq/hHb/2L5XbhyuUR5BIWPHxlQpabnoK89CClfa5/+sNy84/SNMNuZ8FefuHsodTTVieW154,iv:/bSpvlT4HucJKR8Nc8Ydy9wyZsItUrHbwKdcP3Hpo2A=,tag:Xxe2uffx5CPi1bieseRBWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaTZ3cE9YY2ltM0htcWJq
            V1dWbS9QOSthRWJ2V1ZsYXNRR2VnSGFvdFNFCmljS1pIUlNTYVpTUXJPUFNJQ2xp
            RUJ3dE5IcUpHMklwc1VhNWQxd085U1UKLS0tIEkyazN2dEdzYmpqTzZLVUJUMWJI
            UWtlQWh2WEFUVjFNdmF6MXlmMlRQbk0K06EV+WG70RGur0HARvXcAk3qnosFmLoi
            1ysxOBGDjiWER7nDEWjqJ87bFX5DGj15WmLiF2KwMj1ZzzPuScxVXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwxcwgrf2rlthvzg3ywzfvgahe0h6rzt2vqddcny49dvmvv6fg3sqr5dyc
    lastmodified: "2026-09-14T21:59:44Z"
    mac: ENC[AES256_GCM,data:f8OkAFTr46E+qBPQ7b8/0QIZvjksq3twIMubozvebebjQG3EfeS1nElTbn3k87wjg5HmmiT5v7V5Xts2KfP89gARj+bRbp4RWI2OAis4h13oHHYQuU/Ji5YCsTcwUFYgIDBqbQgr6VQ9xjh5kcKAd6Qnw23Vbmf/R2v6/7Nx00c=,iv:1mhbIsaQbhc0iMKECdGv4iR5AdWBXvwpJB40kaSEVJU=,tag:woVCiL6dplD5HHMx2tNlmg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
