#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=env.sh
source "$SCRIPT_DIR/env.sh"

# --- 1. GESTIONE ARGOMENTI ---
PREVIEW=0
if [ "${1:-}" = "--preview" ]; then
    PREVIEW=1
    shift
fi

if [ -n "${1:-}" ]; then
    THEME_NAME="$1"
else
    THEME_NAME=$(ls ~/.config/niri/themes/*.conf | xargs -n 1 basename | sed 's/\.conf//' | tofi --prompt-text " Tema: ")
fi

[ -z "$THEME_NAME" ] && exit 0
THEME_FILE="$HOME/.config/niri/themes/$THEME_NAME.conf"

# --- 2. APPLICAZIONE TEMA NIRI ---
ACTIVE_THEME="$("$SCRIPT_DIR/current_theme.sh" 2>/dev/null || echo "")"
SAVED_WALL=""
SAVED_WALL_EXPANDED=""
if [ -f "$HOME/.config/niri/theme.conf" ]; then
    SAVED_WALL=$(grep '^\$wallpaper' "$HOME/.config/niri/theme.conf" | awk -F= '{print $2}' | xargs)
    SAVED_WALL_EXPANDED="${SAVED_WALL/#\~/$HOME}"
fi

if [ "$PREVIEW" -eq 0 ]; then
    cp "$THEME_FILE" "$HOME/.config/niri/theme.conf"
    # Re-applying the same theme (session start) must not reset a custom wallpaper.
    if [ "$THEME_NAME" = "$ACTIVE_THEME" ] && [ -n "$SAVED_WALL" ] && [ -f "$SAVED_WALL_EXPANDED" ]; then
        sed -i "s|^\$wallpaper =.*|\$wallpaper = ${SAVED_WALL}|" "$HOME/.config/niri/theme.conf"
    fi
fi

rgba_to_hex() {
    local raw="$1"
    if [[ "$raw" =~ rgba\(([0-9a-fA-F]+)\) ]]; then
        local hex="${BASH_REMATCH[1]}"
        echo "#${hex}"
    else
        echo "$raw"
    fi
}

while IFS='=' read -r key value; do
    [[ $key =~ ^\$ ]] || continue
    var_name=$(echo "${key//\$/}" | xargs)
    var_value=$(echo "$value" | xargs)
    declare "$var_name"="$var_value"
done < "$THEME_FILE"

ACTIVE_COLOR1=$(rgba_to_hex "$(echo "$active_border" | grep -o 'rgba([^)]*)' | sed -n '1p')")
ACTIVE_COLOR2=$(rgba_to_hex "$(echo "$active_border" | grep -o 'rgba([^)]*)' | sed -n '2p')")
ACTIVE_ANGLE=$(echo "$active_border" | grep -o '[0-9]\+deg' | sed 's/deg//' || echo 45)
INACTIVE_HEX=$(rgba_to_hex "$inactive_border")
SHADOW_HEX=$(rgba_to_hex "$shadow_color")

if [ -n "$ACTIVE_COLOR2" ]; then
    BORDER_ACTIVE="active-gradient from=\"$ACTIVE_COLOR1\" to=\"$ACTIVE_COLOR2\" angle=$ACTIVE_ANGLE relative-to=\"workspace-view\""
else
    BORDER_ACTIVE="active-color \"$ACTIVE_COLOR1\""
fi

THEME_KDL="$HOME/.config/niri/theme.kdl"

cat > "$THEME_KDL" <<EOF
// Active theme — generated by switch_theme.sh ($THEME_NAME${PREVIEW:+ preview})

layout {
    gaps $gaps_in
    background-color "transparent"

    border {
        on
        width $border_size
        inactive-color "$INACTIVE_HEX"
        $BORDER_ACTIVE
    }

    focus-ring {
        off
    }

EOF

if [[ "$shadow_enabled" == "true" ]]; then
    cat >> "$THEME_KDL" <<EOF
    shadow {
        on
        softness $shadow_range
        color "$SHADOW_HEX"
    }

EOF
else
    cat >> "$THEME_KDL" <<EOF
    shadow {
        off
    }

EOF
fi

cat >> "$THEME_KDL" <<EOF
    struts {
        top 32
    }
}

window-rule {
    geometry-corner-radius $rounding
    clip-to-geometry true
}
EOF

# --- 3. ESTRAZIONE VARIABILI ---
if [ "$PREVIEW" -eq 0 ] && [ -f "$HOME/.config/niri/theme.conf" ]; then
    WALLPAPER=$(grep '^\$wallpaper' "$HOME/.config/niri/theme.conf" | awk -F'=' '{print $2}' | xargs)
else
    WALLPAPER=$(grep '$wallpaper' "$THEME_FILE" | awk -F'=' '{print $2}' | xargs)
fi
WALLPAPER="${WALLPAPER/#\~/$HOME}"
ACCENT=$(grep '$accent_color' "$THEME_FILE" | awk -F'=' '{print $2}' | xargs)
BG=$(grep '$bg_color' "$THEME_FILE" | awk -F'=' '{print $2}' | xargs)
FG=$(grep '$fg_color' "$THEME_FILE" | awk -F'=' '{print $2}' | xargs)
TOFI_SEL=$(grep '$tofi_selection' "$THEME_FILE" | awk -F'=' '{print $2}' | xargs)

# Fallback
[[ ! $ACCENT =~ ^# ]] && ACCENT="#ffffff"
[[ ! $BG =~ ^# ]] && BG="#000000"
[[ ! $FG =~ ^# ]] && FG="#ffffff"

if [[ "$THEME_NAME" == "nero" || "$THEME_NAME" == "black" || "$THEME_NAME" == "earth" || "$THEME_NAME" == "minimal" ]]; then
    ACCENT="#ffffff" ; BG="#000000" ; FG="#ffffff" ; TOFI_SEL="#ff0000"
fi
[ -z "$TOFI_SEL" ] && TOFI_SEL=$ACCENT

# --- 4. SINCRONIZZAZIONE TOFI ---
for CONFIG in "config" "configpowermenu"; do
cat > ~/.config/tofi/$CONFIG <<EOF
anchor=top
width=100%
height=$( [ "$CONFIG" == "config" ] && echo 25 || echo 30 )
horizontal=true
font-size=10
prompt-text=$( [ "$CONFIG" == "config" ] && echo "run:" || echo "Action:" )
font=JetBrainsMono Nerd Font
outline-width=0
border-width=0
min-input-width=120
result-spacing=25
padding-top=5
padding-bottom=5
padding-left=10
padding-right=10
background-color=$BG
text-color=$FG
selection-color=$TOFI_SEL
selection-background=#ffffff22
EOF
done

# --- 5. KITTY & GHOSTTY ---
cat > ~/.config/kitty/theme.conf <<EOF
foreground $FG
background $BG
cursor $ACCENT
EOF

cat > ~/.config/ghostty/theme <<EOF
foreground = $FG
background = $BG
cursor-color = $ACCENT
EOF

FOOT_BG=$(echo $BG | sed 's/#//')
FOOT_FG=$(echo $FG | sed 's/#//')
cat > ~/.config/foot/theme <<EOF
[colors-dark]
foreground=$FOOT_FG
background=$FOOT_BG
selection-foreground=$FOOT_BG
selection-background=$FOOT_FG
EOF

# --- 6. PYTHON: FISH, ZED & BTOP ---
python3 <<EOF
import json, os, colorsys, re

def hex_to_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def rgb_to_hex(rgb):
    return '{:02x}{:02x}{:02x}'.format(int(rgb[0]*255), int(rgb[1]*255), int(rgb[2]*255))

accent = "$ACCENT"
theme_name = "$THEME_NAME"
bg = "$BG"
fg = "$FG"

r, g, b = [x/255.0 for x in hex_to_rgb(accent)]
h, s, v = colorsys.rgb_to_hsv(r, g, b)

if theme_name in ["nero", "black", "earth", "minimal"]:
    syntax_accent = accent
    color_param = "888888"
    color_quote = "aaaaaa"
else:
    syntax_accent = rgb_to_hex(colorsys.hsv_to_rgb(h, s * 0.55, v * 0.85))
    color_param = rgb_to_hex(colorsys.hsv_to_rgb(h, s * 0.35, v * 0.7))
    color_quote = rgb_to_hex(colorsys.hsv_to_rgb(h, s * 0.45, v * 0.8))

fish_path = os.path.expanduser('~/.config/fish/conf.d/theme_colors.fish')
with open(fish_path, 'w') as f:
    f.write(f"set -e fish_color_command\nset -e fish_color_param\n")
    f.write(f"set -g fish_color_command #{syntax_accent} --bold\n")
    f.write(f"set -g fish_color_param #{color_param}\n")
    f.write(f"set -g fish_color_quote #{color_quote}\n")
    f.write(f"set -g fish_color_redirection {accent}\n")
    f.write(f"set -g fish_color_end {accent}\n")
    f.write(f"set -g fish_color_error ff5555\n")
    f.write(f"set -g fish_color_selection --background={accent} --foreground={bg}\n")
    f.write(f"set -g fish_color_autosuggestion 555555\n")

zed_path = os.path.expanduser('~/.config/zed/settings.json')
if os.path.exists(zed_path):
    with open(zed_path, 'r') as f:
        try: zed_data = json.load(f)
        except: zed_data = {}

accent_mute = f"{accent}33"
accent_very_mute = f"{accent}15"

if theme_name in ["nero", "black", "earth", "minimal"]:
    zed_data['experimental.theme_overrides'] = {}
else:
    zed_data['experimental.theme_overrides'] = {
            "background": bg, "editor.background": bg, "pane.background": bg,
            "pane.inactive_background": bg, "side_bar.background": bg,
            "status_bar.background": bg, "title_bar.background": bg,
            "toolbar.background": bg, "tab_bar.background": bg,
            "project_panel.background": bg, "terminal.background": bg,
            "panel.background": bg, "search.background": bg,
            "editor.gutter.background": bg, "menu.background": bg,
            "popover.background": bg, "picker.background": bg,
            "elevated_surface.background": bg, "context_menu.background": bg,
            "dropdown.background": bg, "border": accent_mute,
            "border.variant": accent_mute, "element.active": accent_mute,
            "element.selected": accent_mute, "element.hover": accent_very_mute,
            "tab.active_background": accent_very_mute, "active_tab.border": accent,
            "scrollbar.thumb.background": accent_mute, "text": fg,
            "editor.foreground": fg, "editor.active_line_number.foreground": accent,
            "editor.line_number.foreground": f"#{color_param}",
            "syntax": {
                "comment": {"color": "#606060"},
                "string": {"color": f"#{color_quote}"},
                "keyword": {"color": f"#{syntax_accent}"},
                "function": {"color": f"#{syntax_accent}"},
                "type": {"color": f"#{syntax_accent}"},
                "operator": {"color": f"#{syntax_accent}"},
                "property": {"color": f"#{color_param}"},
                "variable": {"color": fg}
            }
        }

with open(zed_path, 'w') as f:
    json.dump(zed_data, f, indent=4)

btop_theme_dir = os.path.expanduser('~/.config/btop/themes')
if not os.path.exists(btop_theme_dir): os.makedirs(btop_theme_dir)
btop_theme_path = os.path.join(btop_theme_dir, 'dynamic.theme')
with open(btop_theme_path, 'w') as f:
    btop_bg = "" if theme_name in ["nero", "black", "earth", "minimal"] else bg
    f.write(f'theme[main_bg]="{btop_bg}"\ntheme[main_fg]="{fg}"\ntheme[title]="{fg}"\n')
    f.write(f'theme[hi_fg]="{accent}"\ntheme[selected_bg]="#{accent_mute.lstrip("#")}"\n')
    f.write(f'theme[selected_fg]="{accent}"\ntheme[inactive_fg]="#555555"\n')
    f.write(f'theme[proc_misc]="{accent}"\ntheme[cpu_box]="{accent}"\n')
    f.write(f'theme[mem_box]="{accent}"\ntheme[net_box]="{accent}"\n')
    f.write(f'theme[proc_box]="{accent}"\ntheme[div_line]="#333333"\n')
    f.write(f'theme[free_graph]="{accent}"\ntheme[cached_graph]="#{color_param}"\n')
    f.write(f'theme[available_graph]="#{color_quote}"\ntheme[used_graph]="{accent}"\n')
    f.write(f'theme[download_graph]="{accent}"\ntheme[upload_graph]="#{color_param}"\n')

btop_conf_path = os.path.expanduser('~/.config/btop/btop.conf')
if os.path.exists(btop_conf_path):
    with open(btop_conf_path, 'r') as f: content = f.read()
    content = re.sub(r'color_theme = .*', 'color_theme = "dynamic.theme"', content)
    with open(btop_conf_path, 'w') as f: f.write(content)

nvim_dir = os.path.expanduser('~/.config/nvim/lua')
if not os.path.exists(nvim_dir): os.makedirs(nvim_dir)
nvim_path = os.path.join(nvim_dir, 'theme_colors.lua')

def clean_hex(h):
    return h[:7] if h.startswith('#') else f"#{h[:6]}"

with open(nvim_path, 'w') as f:
    f.write(f'return {{\n')
    f.write(f'    bg = "{clean_hex(bg)}",\n')
    f.write(f'    fg = "{clean_hex(fg)}",\n')
    f.write(f'    accent = "{clean_hex(accent)}",\n')
    f.write(f'    syntax = "{clean_hex(syntax_accent)}",\n')
    f.write(f'    param = "{clean_hex(color_param)}",\n')
    f.write(f'    string = "{clean_hex(color_quote)}",\n')
    f.write(f'    selection = "{clean_hex(accent)}",\n')
    f.write(f'}}\n')

EOF

# --- 7. OBSIDIAN ---
OBSIDIAN_SNIPPET="$HOME/obsidian_vault/.obsidian/snippets/system-theme.css"
if [ -d "$HOME/obsidian_vault/.obsidian" ]; then
    if [[ "$THEME_NAME" == "nero" || "$THEME_NAME" == "black" || "$THEME_NAME" == "earth" || "$THEME_NAME" == "minimal" ]]; then
        echo "/* Reset */" > "$OBSIDIAN_SNIPPET"
    else
        cat > "$OBSIDIAN_SNIPPET" <<EOF
:root { --system-accent: $ACCENT; --system-bg: $BG; --system-fg: $FG; }
.theme-dark, .theme-light {
    --accent-component: var(--system-accent) !important;
    --interactive-accent: var(--system-accent) !important;
    --background-primary: var(--system-bg) !important;
    --background-secondary: var(--system-bg) !important;
    --text-normal: var(--system-fg) !important;
}
EOF
    fi
fi

# --- 8. WALLPAPER & REFRESH ---
if [ "$PREVIEW" -eq 1 ]; then
    "$HOME/.config/niri/scripts/set_wallpaper.sh" --no-persist "$WALLPAPER"
else
    "$HOME/.config/niri/scripts/set_wallpaper.sh" "$WALLPAPER"
fi

niri msg action do-screen-transition 2>/dev/null || true
pkill -SIGUSR1 -x kitty 2>/dev/null || true
