{
  imports = [
    ./editors/neovim
    ./editors/nano
    ./emulators/foot
    ./shells/zsh
    ./tools/btop
    ./tools/cava
    ./tools/fastfetch
    ./tools/himalaya
    ./tools/jq
    ./tools/ncdu
    ./tools/ripgrep
    ./tools/ssh
    ./tools/tree
    ./tools/yazi
    ./tools/git
    ./tools/tmux
    ./tools/nodejs
    ./tools/python3
    ./tools/gcc
    ./tools/cmatrix
    ./tools/atuin
    ./tools/libsecret
  ];
}
