font_family family = "JetBrains Mono"

foreground         #FDF9FE
background         #1D1717
cursor             #FDF9FE

active_tab_foreground     #17141C
active_tab_background     #FDF9FE
inactive_tab_foreground   #FDF9FE
inactive_tab_background   #17141C

active_border_color   #FDF9FE
inactive_border_color #17141C
bell_border_color     #3F2F72

color0	#443b3b
color1          #722f2f
color2          #604949
color3          #AA4747
color4          #857474
color5          #BBB3BD
color6          #BBB3BD
color7          #F4EEF5
color8          #AAA7AC
color9          #543F98
color10         #6C6280
color11         #A45EE3
color12         #A59AB1
color13         #F9EEFC
color14         #F9EEFC
color15         #F4EEF5
